class Povezave {
    constructor(polozaj, beseda, pozicija, znak, slika, script, zvok) {
      this._polozaj=polozaj;
      this._beseda=beseda;
      this._pozicija=pozicija;
      this._znak=znak;
      this._slika=slika;
      this._script=script
      this._zvok=zvok;
    }
    get polozaj(){
        return this._polozaj;
    }
    get beseda(){
        return this._beseda;
    }
    get pozicija(){
        return this._pozicija;
    }
    get znak(){
        return this._znak;
    }
    get slika(){
        return this._slika;
    }
    get script(){
        return this._script;
    }
    get zvok(){
        return this._zvok;
    }
  }

const pov = new Array;

pov[0] = new Povezave('H', "ABECEDA", 1, 'A', "mk005a.BMP", "mk005.iaf", "abeceda.wav");
pov[1] = new Povezave('H', "AKVARIJ", 1, 'A', "mk004a.bmp", "mk004.iaf", "akvarij.wav");
pov[2] = new Povezave('H', "ARAŠIDI", 1, 'A', "mk003a.BMP", "mk003.iaf", "arasidi.wav");
pov[3] = new Povezave('H', "ASPIRIN", 1, 'A', "mk001a.bmp", "", "aspirin.wav");
pov[4] = new Povezave('H', "AVTOBUS", 1, 'A', "mk002a.bmp", "mk002.iaf", "avtobus.wav");
pov[5] = new Povezave('H', "ANTENA", 6, 'A', "mk009a.BMP", "mk009.iaf", "antena.wav");
pov[6] = new Povezave('H', "HRUŠKA", 6, 'A', "mk007a.BMP", "mk007.iaf", "hruska.wav");
pov[7] = new Povezave('H', "KNJIGA", 6, 'A', "mk008c.BMP", "mk008.iaf", "knjiga.wav");
pov[8] = new Povezave('H', "SKLEDA", 6, 'A', "mk010a.BMP", "", "skleda.wav");
pov[9] = new Povezave('V', "PAPIGA", 6, 'A', "mk006a.BMP", "mk006.iaf", "papiga.wav");
pov[10] = new Povezave('H', "BAGER", 1, 'B', "mk014a.BMP", "mk014.iaf", "bager.wav");
pov[11] = new Povezave('H', "BISER", 1, 'B', "mk015a.BMP", "mk015.iaf", "biser.wav");
pov[12] = new Povezave('H', "BRANA", 1, 'B', "mk012a.BMP", "", "brana.wav");
pov[13] = new Povezave('H', "BRLOG", 1, 'B', "mk013a.BMP", "mk013.iaf", "brlog.wav");
pov[14] = new Povezave('V', "BREZA", 1, 'B', "mk011a.BMP", "mk011.iaf", "breza.wav");
pov[15] = new Povezave('H', "BOBER", 3, 'B', "mk021a.BMP", "mk021.iaf", "bober.wav");
pov[16] = new Povezave('H', "LABOD", 3, 'B', "mk018a.BMP", "mk018.iaf", "labod.wav");
pov[17] = new Povezave('H', "RIBIČ", 3, 'B', "mk017a.BMP", "mk017.iaf", "ribic.wav");
pov[18] = new Povezave('H', "ROBEC", 3, 'B', "mk016a.BMP", "", "robec.wav");
pov[19] = new Povezave('V', "ROBOT", 3, 'B', "mk020a.BMP", "mk020.iaf", "robot.wav");
pov[20] = new Povezave('H', "ZABOJ", 3, 'B', "mk019a.BMP", "mk019.iaf", "zaboj.wav");
pov[21] = new Povezave('H', "CEKAR", 1, 'C', "mk027a.BMP", "", "cekar.wav");
pov[22] = new Povezave('H', "CEKIN", 1, 'C', "mk024a.BMP", "", "cekin.wav");
pov[23] = new Povezave('H', "CESTA", 1, 'C', "mk025a.BMP", "mk025.iaf", "cesta.wav");
pov[24] = new Povezave('H', "CITRE", 1, 'C', "mk022a.BMP", "", "citre.wav");
pov[25] = new Povezave('H', "COKLE", 1, 'C', "mk023a.BMP", "mk023.iaf", "cokle.wav");
pov[26] = new Povezave('H', "COPAT", 1, 'C', "mk026a.BMP", "", "copat.wav");
pov[27] = new Povezave('H', "RACMAN", 3, 'C', "mk042a.BMP", "mk042.iaf", "racman.wav");
pov[28] = new Povezave('H', "KOSEC", 5, 'C', "mk033a.BMP", "mk173.iaf", "kosec.wav");
pov[29] = new Povezave('H', "LONEC", 5, 'C', "mk030a.BMP", "mk030.iaf", "lonec.wav");
pov[30] = new Povezave('H', "MESEC", 5, 'C', "mk032a.BMP", "mk032.iaf", "mesec.wav");
pov[31] = new Povezave('H', "PALEC", 5, 'C', "mk028a.BMP", "mk028.iaf", "palec.wav");
pov[32] = new Povezave('H', "PEVEC", 5, 'C', "mk031a.BMP", "mk031.iaf", "pevec.wav");
pov[33] = new Povezave('H', "RILEC", 5, 'C', "mk029a.BMP", "mk029.iaf", "rilec.wav");
pov[34] = new Povezave('V', "ČAPLJA", 1, 'Č', "mk034a.BMP", "mk034.iaf", "caplja.wav");
pov[35] = new Povezave('H', "ČEBELA", 1, 'Č', "mk036a.BMP", "mk036.iaf", "cebela.wav");
pov[36] = new Povezave('H', "ČEBULA", 1, 'Č', "mk038a.BMP", "", "cebula.wav");
pov[37] = new Povezave('H', "ČEŠNJI", 1, 'Č', "mk039a.BMP", "mk039.iaf", "cesnji.wav");
pov[38] = new Povezave('H', "ČUTARA", 1, 'Č', "mk037a.BMP", "mk037.iaf", "cutara.wav");
pov[39] = new Povezave('H', "ČEVELJ", 1, 'Č', "mk035a.BMP", "mk035.iaf", "cevelj.wav");
pov[40] = new Povezave('H', "KUČMA", 3, 'Č', "mk045a.BMP", "", "kucma.wav");
pov[41] = new Povezave('H', "LUČKA", 3, 'Č', "mk040a.BMP", "mk040.iaf", "lucka.wav");
pov[42] = new Povezave('H', "MAČEK", 3, 'Č', "mk044a.BMP", "mk044.iaf", "macek.wav");
pov[43] = new Povezave('H', "RAČUN", 3, 'Č', "mk043c.BMP", "mk043.iaf", "racun.wav");
pov[44] = new Povezave('H', "TAČKA", 3, 'Č', "mk041a.BMP", "mk041.iaf", "tacka.wav");
pov[45] = new Povezave('H', "DARILO", 1, 'D', "mk055a.BMP", "", "darilo.wav");
pov[46] = new Povezave('H', "DELFIN", 1, 'D', "mk054a.BMP", "mk054.iaf", "delfin.wav");
pov[47] = new Povezave('H', "DEŽNIK", 1, 'D', "mk052a.BMP", "mk052.iaf", "deznik.wav");
pov[48] = new Povezave('H', "DIMNIK", 1, 'D', "mk051a.BMP", "mk051.iaf", "dimnik.wav");
pov[49] = new Povezave('H', "DOMINE", 1, 'D', "mk053a.BMP", "mk053.iaf", "domine.wav");
pov[50] = new Povezave('H', "PEDAL", 3, 'D', "mk050a.BMP", "mk050.iaf", "pedal.wav");
pov[51] = new Povezave('H', "SADJE", 3, 'D', "mk047a.BMP", "", "sadje.wav");
pov[52] = new Povezave('H', "SEDEŽ", 3, 'D', "mk049a.BMP", "", "sedez.wav");
pov[53] = new Povezave('H', "LADJA", 3, 'D', "mk046a.BMP", "mk046.iaf", "ladja.wav");
pov[54] = new Povezave('H', "ZIDAK", 3, 'D', "mk048a.BMP", "", "zidak.wav");
pov[55] = new Povezave('H', "KEPA", 2, 'E', "mk058a.BMP", "mk058.iaf", "kepa.wav");
pov[56] = new Povezave('H', "MESO", 2, 'E', "mk057a.BMP", "", "meso.wav");
pov[57] = new Povezave('H', "PETA", 2, 'E', "mk060a.BMP", "", "peta.wav");
pov[58] = new Povezave('H', "REPA", 2, 'E', "mk056a.BMP", "mk056.iaf", "repa.wav");
pov[59] = new Povezave('H', "VEJA", 2, 'E', "mk059a.BMP", "mk059.iaf", "veja.wav");
pov[60] = new Povezave('H', "KARTE", 5, 'E', "mk062a.BMP", "mk062.iaf", "karte.wav");
pov[61] = new Povezave('H', "PERJE", 5, 'E', "mk064a.BMP", "", "perje.wav");
pov[62] = new Povezave('H', "SADJE", 5, 'E', "mk047a.BMP", "", "sadje.wav");
pov[63] = new Povezave('H', "SONCE", 5, 'E', "mk061a.BMP", "mk061.iaf", "sonce.wav");
pov[64] = new Povezave('H', "ZELJE", 5, 'E', "mk065a.BMP", "mk065.iaf", "zelje.wav");
pov[65] = new Povezave('H', "FAZAN", 1, 'F', "mk069a.BMP", "mk069.iaf", "fazan.wav");
pov[66] = new Povezave('V', "FIKUS", 1, 'F', "mk066a.BMP", "", "fikus.wav");
pov[67] = new Povezave('H', "FIŽOL", 1, 'F', "mk067a.BMP", "mk067.iaf", "fizol.wav");
pov[68] = new Povezave('H', "FRAČA", 1, 'F', "mk068a.BMP", "mk068.iaf", "fraca.wav");
pov[69] = new Povezave('H', "MIKROFON", 6, 'F', "mk071a.BMP", "mk071.iaf", "mikrofon.wav");
pov[70] = new Povezave('H', "SAKSOFON", 6, 'F', "mk073a.BMP", "", "saksofon.wav");
pov[71] = new Povezave('H', "SEMAFOR", 5, 'F', "mk070a.BMP", "mk070.iaf", "semafor.wav");
pov[72] = new Povezave('H', "TELEFON", 5, 'F', "mk072a.BMP", "mk072.iaf", "telefon.wav");
pov[73] = new Povezave('H', "GAMS", 1, 'G', "mk077a.BMP", "mk077.iaf", "gams.wav");
pov[74] = new Povezave('H', "GOBE", 1, 'G', "mk075a.BMP", "", "gobe.wav");
pov[75] = new Povezave('V', "GOZD", 1, 'G', "mk078a.BMP", "", "gozd.wav");
pov[76] = new Povezave('H', "GRAD", 1, 'G', "mk074a.BMP", "mk074.iaf", "grad.wav");
pov[77] = new Povezave('H', "GUMB", 1, 'G', "mk076a.BMP", "", "gumb.wav");
pov[78] = new Povezave('V', "NOGA", 3, 'G', "mk081a.BMP", "mk081.iaf", "noga.wav");
pov[79] = new Povezave('H', "ŽAGA", 3, 'G', "mk080a.BMP", "mk080.iaf", "zaga.wav");
pov[80] = new Povezave('H', "ŽOGA", 3, 'G', "mk079a.BMP", "mk079.iaf", "zoga.wav");
pov[81] = new Povezave('V', "HARFA", 1, 'H', "mk090a.BMP", "", "harfa.wav");
pov[82] = new Povezave('H', "HLAČE", 1, 'H', "mk089a.BMP", "", "hlace.wav");
pov[83] = new Povezave('H', "HLODI", 1, 'H', "mk087a.BMP", "", "hlodi.wav");
pov[84] = new Povezave('V', "HRČEK", 1, 'H', "mk086d.BMP", "mk086.iaf", "hrcek.wav");
pov[85] = new Povezave('H', "HROŠČ", 1, 'H', "mk088a.BMP", "mk088.iaf", "hrosc.wav");
pov[86] = new Povezave('H', "DIHUR", 3, 'H', "mk084a.BMP", "mk084.iaf", "dihur.wav");
pov[87] = new Povezave('H', "JAHTA", 3, 'H', "mk083a.BMP", "", "jahta.wav");
pov[88] = new Povezave('V', "KUHAR", 3, 'H', "mk082a.BMP", "mk082.iaf", "kuhar.wav");
pov[89] = new Povezave('H', "PEHAR", 3, 'H', "mk085a.BMP", "mk085.iaf", "pehar.wav");
pov[90] = new Povezave('H', "IGLA", 1, 'I', "mk096a.BMP", "mk096.iaf", "igla.wav");
pov[91] = new Povezave('H', "IGLU", 1, 'I', "mk097a.BMP", "mk097.iaf", "iglu.wav");
pov[92] = new Povezave('V', "IRIS", 1, 'I', "mk098a.BMP", "", "iris.wav");
pov[93] = new Povezave('V', "KITA", 2, 'I', "mk091a.BMP", "", "kita.wav");
pov[94] = new Povezave('H', "LIST", 2, 'I', "mk092a.BMP", "mk092.iaf", "list.wav");
pov[95] = new Povezave('H', "MILO", 2, 'I', "mk095a.BMP", "mk095.iaf", "milo.wav");
pov[96] = new Povezave('H', "PILA", 2, 'I', "mk094a.BMP", "mk094.iaf", "pila.wav");
pov[97] = new Povezave('H', "SITO", 2, 'I', "mk093a.BMP", "mk093.iaf", "sito.wav");
pov[98] = new Povezave('V', "JADRO", 1, 'J', "mk099a.BMP", "mk099.iaf", "jadro.wav");
pov[99] = new Povezave('H', "JAJCE", 1, 'J', "mk101a.BMP", "", "jajce.wav");
pov[100] = new Povezave('H', "JASLI", 1, 'J', "mk100a.BMP", "", "jasli.wav");
pov[101] = new Povezave('H', "JELEN", 1, 'J', "mk102a.BMP", "mk102.iaf", "jelen.wav");
pov[102] = new Povezave('H', "KLJUČ", 3, 'J', "mk105a.BMP", "", "kljuc.wav");
pov[103] = new Povezave('H', "PAJAC", 3, 'J', "mk104a.BMP", "mk104.iaf", "pajac.wav");
pov[104] = new Povezave('V', "PAJEK", 3, 'J', "mk103a.BMP", "mk103.iaf", "pajek.wav");
pov[105] = new Povezave('H', "ZAJEC", 3, 'J', "mk106a.BMP", "mk106.iaf", "zajec.wav");
pov[106] = new Povezave('H', "KAKTUS", 1, 'K', "mk114a.BMP", "", "kaktus.wav");
pov[107] = new Povezave('H', "KAMELA", 1, 'K', "mk115a.BMP", "mk115.iaf", "kamela.wav");
pov[108] = new Povezave('H', "KITARA", 1, 'K', "mk113a.BMP", "mk113.iaf", "kitara.wav");
pov[109] = new Povezave('H', "KOŠARA", 1, 'K', "mk112a.BMP", "", "kosara.wav");
pov[110] = new Povezave('H', "KROKAR", 1, 'K', "mk111a.BMP", "mk111.iaf", "krokar.wav");
pov[111] = new Povezave('V', "LOK", 3, 'K', "mk109a.BMP", "mk109.iaf", "lok.wav");
pov[112] = new Povezave('V', "MAK", 3, 'K', "mk107a.BMP", "", "mak.wav");
pov[113] = new Povezave('V', "PEK", 3, 'K', "mk110a.BMP", "mk110.iaf", "pek.wav");
pov[114] = new Povezave('H', "RAK", 3, 'K', "mk108a.BMP", "mk108.iaf", "rak.wav");
pov[115] = new Povezave('V', "LESTEV", 1, 'L', "mk124a.BMP", "", "lestev.wav");
pov[116] = new Povezave('H', "LEŠNIK", 1, 'L', "mk121a.BMP", "", "lesnik.wav");
pov[117] = new Povezave('H', "LETALO", 1, 'L', "mk122a.BMP", "mk122.iaf", "letalo.wav");
pov[118] = new Povezave('H', "LIMONA", 1, 'L', "mk120a.BMP", "mk120.iaf", "limona.wav");
pov[119] = new Povezave('H', "LISICA", 1, 'L', "mk123a.BMP", "mk123.iaf", "lisica.wav");
pov[120] = new Povezave('H', "PLUG", 2, 'L', "mk116a.BMP", "", "plug.wav");
pov[121] = new Povezave('H', "SLAK", 2, 'L', "mk117a.BMP", "", "slak.wav");
pov[122] = new Povezave('H', "SLAP", 2, 'L', "mk119a.BMP", "mk119.iaf", "slap.wav");
pov[123] = new Povezave('H', "VLAK", 2, 'L', "mk118a.BMP", "mk118.iaf", "vlak.wav");
pov[124] = new Povezave('H', "MALINA", 1, 'M', "mk130a.BMP", "", "malina.wav");
pov[125] = new Povezave('H', "MEDVED", 1, 'M', "mk129a.BMP", "mk129.iaf", "medved.wav");
pov[126] = new Povezave('H', "METULJ", 1, 'M', "mk131a.BMP", "mk131.iaf", "metulj.wav");
pov[127] = new Povezave('H', "MORNAR", 1, 'M', "mk132a.BMP", "mk132.iaf", "mornar.wav");
pov[128] = new Povezave('V', "MOTIKA", 1, 'M', "mk128a.BMP", "", "motika.wav");
pov[129] = new Povezave('V', "LAMA", 3, 'M', "mk125a.BMP", "mk125.iaf", "lama.wav");
pov[130] = new Povezave('H', "SOMI", 3, 'M', "mk126a.BMP", "mk126.iaf", "somi.wav");
pov[131] = new Povezave('V', "ŠEMA", 3, 'M', "mk127a.BMP", "mk127.iaF", "sema.wav");
pov[132] = new Povezave('H', "NIT", 1, 'N', "mk139a.BMP", "mk139.iaf", "nit.wav");
pov[133] = new Povezave('V', "NOJ", 1, 'N', "mk137a.BMP", "mk137.iaf", "noj.wav");
pov[134] = new Povezave('H', "NOS", 1, 'N', "mk138a.BMP", "mk138.iaf", "nos.wav");
pov[135] = new Povezave('H', "BALON", 5, 'N', "mk134a.BMP", "mk134.iaf", "balon.wav");
pov[136] = new Povezave('H', "BOBEN", 5, 'N', "mk133a.BMP", "mk133.iaf", "boben.wav");
pov[137] = new Povezave('H', "FAZAN", 5, 'N', "mk069a.BMP", "mk069.iaf", "fazan.wav");
pov[138] = new Povezave('H', "JELEN", 5, 'N', "mk102a.BMP", "mk102.iaf", "jelen.wav");
pov[139] = new Povezave('H', "OBLAK", 1, 'O', "mk142a.BMP", "mk142.iaf", "oblak.wav");
pov[140] = new Povezave('H', "OČALA", 1, 'O', "mk143a.BMP", "mk143.iaf", "ocala.wav");
pov[141] = new Povezave('V', "OKLEP", 1, 'O', "mk144a.BMP", "mk144.iaf", "oklep.wav");
pov[142] = new Povezave('V', "OMARA", 1, 'O', "mk140a.BMP", "mk140.iaf", "omara.wav");
pov[143] = new Povezave('H', "OPICA", 1, 'O', "mk141a.BMP", "mk141.iaf", "opica.wav");
pov[144] = new Povezave('H', "GOSKA", 2, 'O', "mk145a.BMP", "mk145.iaf", "goska.wav");
pov[145] = new Povezave('V', "KOŠ", 2, 'O', "mk146a.BMP", "mk146.iaf", "koss.wav");
pov[146] = new Povezave('H', "NOŽ", 2, 'O', "mk147a.BMP", "", "noz.wav");
pov[147] = new Povezave('V', "SOD", 2, 'O', "mk148a.BMP", "", "sod.wav");
pov[148] = new Povezave('H', "PACKA", 1, 'P', "mk151a.BMP", "mk151.iaf", "packa.wav");
pov[149] = new Povezave('H', "PAJAC", 1, 'P', "mk104a.BMP", "mk104.iaf", "pajac.wav");
pov[150] = new Povezave('V', "PAJEK", 1, 'P', "mk103a.BMP", "mk103.iaf", "pajek.wav");
pov[151] = new Povezave('H', "PAKET", 1, 'P', "mk150a.BMP", "", "paket.wav");
pov[152] = new Povezave('H', "PISMO", 1, 'P', "mk152a.BMP", "mk152.iaf", "pismo.wav");
pov[153] = new Povezave('H', "KAPA", 3, 'P', "mk218a.BMP", "", "kapa.wav");
pov[154] = new Povezave('H', "KEPA", 3, 'P', "mk058a.BMP", "mk058.iaf", "kepa.wav");
pov[155] = new Povezave('V', "PIPA", 3, 'P', "mk154a.BMP", "mk154.iaf", "pipa.wav");
pov[156] = new Povezave('H', "REPA", 3, 'P', "mk056a.BMP", "mk056.iaf", "repa.wav");
pov[157] = new Povezave('H', "RIBA", 1, 'R', "mk164a.BMP", "mk164.iaf", "riba.wav");
pov[158] = new Povezave('H', "ROKA", 1, 'R', "mk165a.BMP", "mk165.iaf", "roka.wav");
pov[159] = new Povezave('H', "ROŽE", 1, 'R', "mk163a.BMP", "", "roze.wav");
pov[160] = new Povezave('V', "DRVAR", 5, 'R', "mk196a.BMP", "mk159.iaf", "drvar.wav");
pov[161] = new Povezave('H', "KIPAR", 5, 'R', "mk161a.BMP", "mk161.iaf", "kipar.wav");
pov[162] = new Povezave('V', "KUHAR", 5, 'R', "mk082a.BMP", "mk082.iaf", "kuhar.wav");
pov[163] = new Povezave('V', "METER", 5, 'R', "mk162a.BMP", "", "meter.wav");
pov[164] = new Povezave('H', "ZIDAR", 5, 'R', "mk207a.BMP", "mk160.iaf", "zidar.wav");
pov[165] = new Povezave('H', "SALAMA", 1, 'S', "mk169a.BMP", "mk169.iaf", "salama.wav");
pov[166] = new Povezave('V', "SMREKA", 1, 'S', "mk170a.BMP", "mk170.iaf", "smreka.wav");
pov[167] = new Povezave('H', "SNEŽAK", 1, 'S', "mk166a.BMP", "mk166.iaf", "snezak.wav");
pov[168] = new Povezave('H', "STOŽEC", 1, 'S', "mk168a.BMP", "", "stozec.wav");
pov[169] = new Povezave('H', "STREHA", 1, 'S', "mk167a.BMP", "mk167.iaf", "streha.wav");
pov[170] = new Povezave('H', "KOSEC", 3, 'S', "mk033a.BMP", "mk173.iaf", "kosec.wav");
pov[171] = new Povezave('H', "MESAR", 3, 'S', "mk171d.BMP", "mk171.iaf", "mesar.wav");
pov[172] = new Povezave('H', "MESEC", 3, 'S', "mk172a.BMP", "mk172.iaf", "mesec.wav");
pov[173] = new Povezave('H', "MESTO", 3, 'S', "mk174a.BMP", "", "mesto.wav");
pov[174] = new Povezave('H', "ŠČETKA", 1, 'Š', "mk180a.BMP", "mk180.iaf", "scetka.wav");
pov[175] = new Povezave('H', "ŠILČEK", 1, 'Š', "mk181a.BMP", "mk181.iaf", "silcek.wav");
pov[176] = new Povezave('H', "ŠKARJE", 1, 'Š', "mk182a.BMP", "mk182.iaf", "skarje.wav");
pov[177] = new Povezave('H', "ŠKOREC", 1, 'Š', "mk179a.BMP", "mk179.iaf", "skorec.wav");
pov[178] = new Povezave('H', "KOŠARA", 3, 'Š', "mk112a.BMP", "", "kosara.wav");
pov[179] = new Povezave('H', "KUŠČAR", 3, 'Š', "mk177a.BMP", "mk177.iaf", "kuscar.wav");
pov[180] = new Povezave('H', "POŠTAR", 3, 'Š', "mk175a.BMP", "mk175.iaf", "postar.wav");
pov[181] = new Povezave('V', "TABLA", 1, 'T', "mk186a.BMP", "mk186.iaf", "tabla.wav");
pov[182] = new Povezave('H', "TORBA", 1, 'T', "mk185a.BMP", "mk185.iaf", "torba.wav");
pov[183] = new Povezave('H', "TORTA", 1, 'T', "mk184a.BMP", "mk184.iaf", "torta.wav");
pov[184] = new Povezave('H', "TRNEK", 1, 'T', "mk183a.BMP", "mk183.iaf", "trnek.wav");
pov[185] = new Povezave('V', "METER", 3, 'T', "mk162a.BMP", "", "meter.wav");
pov[186] = new Povezave('V', "METLA", 3, 'T', "mk190a.BMP", "mk190.iaf", "metla.wav");
pov[187] = new Povezave('H', "ŠOTOR", 3, 'T', "mk189a.BMP", "mk189.iaf", "sotor.wav");
pov[188] = new Povezave('H', "VETER", 3, 'T', "mk188a.BMP", "mk188.iaf", "veter.wav");
pov[189] = new Povezave('V', "UHO", 1, 'U', "mk219a.BMP", "", "uho.wav");
pov[190] = new Povezave('H', "URA", 1, 'U', "mk216a.BMP", "mk216.iaf", "ura.wav");
pov[191] = new Povezave('H', "UTA", 1, 'U', "mk217a.BMP", "mk217.iaf", "uta.wav");
pov[192] = new Povezave('H', "KUNA", 2, 'U', "mk192a.BMP", "mk192.iaf", "kuna.wav");
pov[193] = new Povezave('V', "KUŽA", 2, 'U', "mk191a.BMP", "mk191.iaf", "kuza.wav");
pov[194] = new Povezave('H', "MUHA", 2, 'U', "mk194a.BMP", "mk194.iaf", "muha.wav");
pov[195] = new Povezave('H', "PUMA", 2, 'U', "mk193a.BMP", "mk193.iaf", "puma.wav");
pov[196] = new Povezave('H', "VEDRO", 1, 'V', "mk199a.BMP", "", "vedro.wav");
pov[197] = new Povezave('H', "VENEC", 1, 'V', "mk201a.BMP", "", "venec.wav");
pov[198] = new Povezave('V', "VITEZ", 1, 'V', "mk202a.BMP", "mk202.iaf", "vitez.wav");
pov[199] = new Povezave('H', "VLAK", 1, 'V', "mk118a.BMP", "mk118.iaf", "vlak.wav");
pov[200] = new Povezave('V', "DRVAR", 3, 'V', "mk196a.BMP", "mk159.iaf", "drvar.wav");
pov[201] = new Povezave('H', "KOVAČ", 3, 'V', "mk198a.BMP", "mk198.iaf", "kovac.wav");
pov[202] = new Povezave('V', "LOVEC", 3, 'V', "mk195a.BMP", "mk195.iaf", "lovec.wav");
pov[203] = new Povezave('H', "PEVKA", 3, 'V', "mk197a.BMP", "mk197.iaf", "pevka.wav");
pov[204] = new Povezave('H', "ZABOJ", 1, 'Z', "mk019a.BMP", "mk019.iaf", "zaboj.wav");
pov[205] = new Povezave('H', "ZEBRA", 1, 'Z', "mk206a.BMP", "", "zebra.wav");
pov[206] = new Povezave('H', "ZELJE", 1, 'Z', "mk065a.BMP", "mk065.iaf", "zelje.wav");
pov[207] = new Povezave('H', "ZIDAR", 1, 'Z', "mk207a.BMP", "mk160.iaf", "zidar.wav");
pov[208] = new Povezave('H', "KOZA", 3, 'Z', "mk205a.BMP", "mk205.iaf", "koza.wav");
pov[209] = new Povezave('V', "MIZA", 3, 'Z', "mk204a.BMP", "", "miza.wav");
pov[210] = new Povezave('V', "VAZA", 3, 'Z', "mk203a.BMP", "mk203.iaf", "vaza.wav");
pov[211] = new Povezave('H', "ŽELVA", 1, 'Ž', "mk213a.BMP", "mk213.iaf", "zelva.wav");
pov[212] = new Povezave('H', "ŽLICA", 1, 'Ž', "mk214a.BMP", "", "zlica.wav");
pov[213] = new Povezave('V', "ŽOLNA", 1, 'Ž', "mk215a.BMP", "mk215.iaf", "zolna.wav");
pov[214] = new Povezave('H', "KRIŽ", 4, 'Ž', "mk211a.BMP", "", "kriz.wav");
pov[215] = new Povezave('H', "MROŽ", 4, 'Ž', "mk210a.BMP", "", "mroz.wav");
pov[216] = new Povezave('H', "POLŽ", 4, 'Ž', "mk212a.BMP", "mk212.iaf", "polz.wav");